# Generated by Django 4.0.3 on 2022-03-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_view_not_moderated_list', 'Can view not moderated list')]},
        ),
    ]
